version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    ports:
      - "5001:5001"
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0satellite0
      - MYSQL_DATABASE=mimir
    ports:
      - "32000:3306"